config/routes.rb
Rails.application.routes.draw do

  get "install/setting"
  get "install/user"
  get "install/setcity"

  get "v2"=>'main#index'

  resources :forums
  resources :topics
  resources :logs

  resources :provinces
  resources :routes
  resources :asks, :path => 'wenda'

  match 'login' => 'users#login', :as => 'login', :via => [:get, :post]
  match 'register' => 'users#register', :as => 'register', :via => [:get, :post]
  post 'users/create' => 'users#create'
  post 'users/ajax' => 'users#ajax'
  get 'user/logout' => 'users#logout'

  resources :u, :only => [:show] do |u|
    member do
      match '/albums'=>'u#albums',:as=>'albums',:via=>[:get]
      match '/albums_upload'=>'u#albums_upload',:as=>'albums_upload',:via=>[:get,:post]
      match '/album/:aid' => 'u#album', :constraints => {:aid => /\d/}, :as => 'album_show',:via=>[:get]
    end
  end

  resources :places do
    member do
      get 'photos'
      post 'wantgoto'
      post 'beento'
    end
    collection do
      match 'city/:name' => 'places#city', :constraints => {:name => /[a-zA-z1-9]+/}, :as => 'city',:via=>:get
      match 'area/:name' => 'places#area', :constraints => {:name => /[a-zA-z1-9]+/}, :as => 'area',:via=>:get
    end
  end

  resources :photos do
    collection do
      post :upload
    end
  end

  resources :asks, :path => 'wenda'

  resources :guides

  resources :comments do
    collection do
      get 'list', :to => "comments#list",:as => 'list'
      get :show
      get :getone
    end
  end

  resources :forums,:except => [:show] do
    collection do
      resources :topics,:except => [:show] do
        collection do
          get 'post', :to => "topics#new",:as => 'post'
          get ':id', :to => "topics#show",:constraints => {:id => /[\d]+/},:as => 'show'
        end
      end
    end
  end

  root 'main#two', :as => 'main'

  get "admin" => 'admin#frame', :as => 'admin'
  post 'admin/login' => 'admin#login'
  namespace :admin do |admin|
    resources :ads
    resources :main
    resources :forums
    resources :places
    resources :users
    resources :options
    resources :comments
    resources :recommends
    resources :managers
    resources :guides
    resources :articles
  end

  match ':controller(/:action(/:id))(.:format)', :constraints => {:id => /[\d]+/}, :via => [:get]

end

app/models/recommend.rb
#coding: utf-8
class Recommend < ActiveRecord::Base
  #attr_accessible :hits, :img_path,:img_ids, :intro, :is_close, :is_fixed, :name, :order_num, :redirect, :category
  validates_presence_of :name
  validates_presence_of :redirect
  validates_presence_of :category
  #validates_format_of :redirect,:with =>/(^$)|(^(http|https)://[a-z0-9] ([-.]{1}[a-z0-9] )*.[a-z]{2,5}(([0-9]{1,5})?/.*)?$)/ix
  #validates_format_of  :email, :message => "邮箱格式不正确!", :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  #在rails的model中，生产环境中是缓存类的，比如一个Country模型中定义一个常量表示所有的国家（当model加载的时候将会做Country.all查询）
  ALL_CATEGORY={:home => '首页', :place => '目的地', :route => '路线'}

  #幻灯片
  scope :focus,-> {select("id,name,img_path,redirect,category").order('is_fixed DESC,order_num ASC,id DESC')}
  #scope :focus,select("id,name,img_path,redirect,category").where("is_close=?",false).order('is_fixed DESC,order_num ASC,id DESC')
  #rails3写法
  #scope :cat,lambda { |category| where("category=?",category)}
  #rails4写法
  scope :cat, ->(category) { where(:category => category) }

  before_save :set_boolean

  private
  def set_boolean
  end

end

app/controllers/admin/recommends_controller.rb
#coding: utf-8
class Admin::RecommendsController < AdminController

  #目的地列表
  def index
    conditions=Array.new
    if params[:q]
      conditions << "name LIKE ?"
      conditions << "%#{params[:q]}%"
    end
    @recommends=Recommend.paginate(:page => params[:page], :per_page => 10, :conditions => conditions)

  end

  #添加记录
  def new
    @recommend = Recommend.new
  end

  #编辑记录
  def edit
    @recommend = Recommend.find(params[:id])
    @pics=(@recommend.img_ids.blank?)?[]:Attached.where(:id=>@recommend.img_ids.split(','))
  end

  #提交新建
  def create
    @recommend = Recommend.new(params[:recommend])
    if @recommend.save
      respond :redirect_to => admin_recommends_path, :success =>I18n.t('activerecord.models.recommend')+'添加成功'
    else
      #render :text => @place.errors.full_messages
      respond :action => 'new', :error => @recommend.errors.full_messages
    end
  end

  #保存修改
  def update
    @recommend = Recommend.find(params[:id])
    if @recommend.update_attributes(params[:recommend])
      respond :redirect_to => admin_recommends_path, :success => '资料修改成功'
    else
      respond :action => 'edit', :error => @recommend.errors.full_messages
    end
  end

  #删除
  def destroy
    @recommend = Recommend.find(params[:id])
    @recommend.destroy
    respond :redirect_to => admin_recommends_path, :success => '资料删除成功'
  end

end

app/helpers/admin/recommends_helper.rb
module Admin::RecommendsHelper
end

app/views/admin/recommends/_form.html.erb
<% content_for:head do %>
    <link rel="stylesheet" type="text/css" href="/static/uploadify/uploadify.css">
    <script type="text/javascript" src="/static/uploadify/jquery.uploadify-3.1.min.js"></script>
<% end %>

<%
   if @recommend.new_record?
     method_path=admin_recommends_path
   else
     method_path=admin_recommend_path(@recommend.id)
   end
%>

<%= form_for(@recommend, :url => method_path, :html => {:id => 'form1', :class => 'form-horizontal'}) do |f| %>

    <%= block_alert @recommend %>

    <div class="control-group">
      <%= f.label :category, :class => 'control-label' %>
      <div class="controls">
        <%= select("recommend", "category", Recommend::ALL_CATEGORY.invert, {:include_blank => '选择分类'}) %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :name, '自定义标题', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'input-xxlarge' %>
      </div>
    </div>


    <div class="control-group">
      <%= f.label :order_num, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :order_num, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :intro, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :intro, :rows => '3', :class => 'span10' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :redirect, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :redirect, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="control-group" id="uploadify_preview" style="display:<%= (@pics.blank?) ? 'none' : 'block' %>">
      <div class="controls">
        <ul>
          <% if @pics %>
              <% @pics.each do |p| %>
                  <li><img src="<%= img_path p %>" alt=""/></li>
              <% end %>
          <% end %>
          <li id="includBefore" style="display: none"></li>
        </ul>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.hidden_field :img_ids, :class => 'input-xxlarge', :id => "img_ids" %>
        <%= f.hidden_field :img_path, :class => 'input-xxlarge', :id => "img_path" %>
        <input type="file" name="file_upload" id="file_upload"/>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :is_close,'属性', :class => 'control-label' %>

      <div class="controls">
        <label class="checkbox inline">
          <input type="checkbox" name="recommend[is_close]" <%= 'checked' if @recommend.is_close %> > 关闭
        </label>

        <label class="checkbox inline">
        <input type="checkbox" name="recommend[is_fixed]" <%= 'checked' if @recommend.is_fixed %>> 置顶
        </label>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.button :class => "btn btn-primary", :id => 'submit_button',:disable_with => "提交中..." %>
        <%= f.button '取消',:type=>"button",:class => "btn",:id=>'cancel_button',:onclick=>'history.back()'  %>
      </div>
    </div>
<% end %>

<script type="text/javascript">
    readyScript.bind = function () {
        $('#form1').bind("submit", function (e) {
            e.preventDefault();
            new ajaxForm($(this), {
                dataType: 'json'
            }).send();
        });
        var uploader = new go_uploader();
        uploader.preview();
        uploader.uploadify();
    }
</script>

app/views/admin/recommends/edit.html.erb
<div class="container-fluid">
  <div class="row-fluid">

    <div class="area-top clearfix">
      <div class="pull-left header">
        <h3 class="title">
          <i class="icon-edit"></i>
          编辑<%= I18n.t 'activerecord.models.recommend' %>
        </h3>
        <h5>
          <%= Time.now %>
        </h5>
      </div>

    </div>
  </div>
</div>


<div class="container-fluid padded">


  <div class="row-fluid">
    <div class="span12">

      <div class="box">
        <div class="box-header">
          <span class="title"><i class="icon-warning-sign"></i> 修改记录</span>
        </div>

        <div class="box-content">
          <div class="container-fluid padded">
            <div class="row-fluid">
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/admin/recommends/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="area-top clearfix">
      <div class="pull-left header">
        <h3 class="title">
          <i class="icon-flag"></i>
          <%= I18n.t 'activerecord.models.recommend' %>


          星期<%=Time.now.wday %>
          <%= time_ago_in_words(Time.new-13.second,true) %>前
          <%= distance_of_time_in_words(Time.new, Time.new + 15.seconds, true) %>前
        </h3>
        <h5> </h5>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid padded">
  <div class="row-fluid">

    <%= block_alert %>

    <div class="box">


      <div class="box-header">
        <span class="title"><i class="icon-list"></i>&nbsp;所有记录</span>
        <ul class="box-toolbar">
          <li>
            <form class="fill-up" style="width:200px">
              <label class="input-with-submit">
                <input name="q" type="text" placeholder="Search...">
                <button type="submit" class="submit-icon">
                  <i class="icon-search"></i>
                </button>
              </label>
            </form>
          </li>


          <li class="toolbar-link">
            <a href="#" data-toggle="dropdown"><i class="icon-cog"></i></a>
            <ul class="dropdown-menu">
              <li><a href="<%= new_admin_recommend_path %>"><i class="icon-plus-sign"></i> Add</a></li>
              <li><a href="#"><i class="icon-remove-sign"></i> Remove</a></li>
              <li><a href="#"><i class="icon-pencil"></i> Edit</a></li>
            </ul>
          </li>
        </ul>
      </div>

      <div class="box-content">
        <table class="table table-normal" id="record_table">
          <thead>
          <tr>
            <td class="record-checkbox">审核</td>
            <td class="record-title">标题</td>
            <td class="record-cmthit">类别</td>
            <td class="record-author">预览</td>
            <td class="record-date">发布日期</td>
            <td class="record-operate">操作</td>
          </tr>
          </thead>

          <tbody>

          <% @recommends.each do |r| %>
              <tr id="record_<%= r.id %>">
                <td class="record-checkbox"><input type="checkbox" name="cid[]" value="1"></td>
                <td class="record-title"><a href="<%= edit_admin_recommend_path(r, :format => 'html') %>"><%= r.name %></a></td>
                <td class="record-cmthit"><%= r[:category] %></td>
                <td class="record-author"><a href="<%= r.redirect%>" target="_blank">预览</a></td>
                <td class="record-date"><%= to_pretty(r.created_at) %>
                  <% r.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                <td class="record-operate">
                  <a href="<%= admin_recommend_path(r) %>"><i class="icon-search"></i></a>
                  <a href="<%= edit_admin_recommend_path(r) %>" "><i class="icon-edit"></i></a>
                  <a href="javascript:;"><i class="icon-remove" cid="<%= r.id %>"></i></a>
                </td>
              </tr>
          <% end %>

          </tbody>
        </table>

        <div class="table-footer">

          <div class="dataTables_info" id="DataTables_Table_0_info"><%= page_entries_info @recommends, :html => false %></div>
          <%= go_pager @recommends %>

        </div>

      </div>
    </div>
  </div>

</div>
<script type="text/javascript">
    readyScript.bind = function () {
        $("#record_table .icon-remove").each(function () {
            $(this).bind("click", function () {
                var cid=$(this).attr('cid');
                new candyLayer().deleteRecord(cid,{
                    url:'/admin/recommends/'+cid
                });
            });
        });
    }
</script>

app/views/admin/recommends/new.html.erb
<div class="container-fluid">
  <div class="row-fluid">

    <div class="area-top clearfix">
      <div class="pull-left header">
        <h3 class="title">
          <i class="icon-edit"></i>
          新增<%= I18n.t 'activerecord.models.recommend' %>
        </h3>
        <h5>
          A subtitle can be added here
        </h5>
      </div>

    </div>
  </div>
</div>


<div class="container-fluid padded">


  <div class="row-fluid">
    <div class="span12">

      <div class="box">
        <div class="box-header">
          <span class="title"><i class="icon-warning-sign"></i> Forms with validation</span>
        </div>

        <div class="box-content">
          <div class="container-fluid padded">
            <div class="row-fluid">
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>