config/routes.rb
Rails.application.routes.draw do

  get "install/setting"
  get "install/user"
  get "install/setcity"

  get "v2"=>'main#index'

  resources :forums
  resources :topics
  resources :logs

  resources :provinces
  resources :routes
  resources :asks, :path => 'wenda'

  match 'login' => 'users#login', :as => 'login', :via => [:get, :post]
  match 'register' => 'users#register', :as => 'register', :via => [:get, :post]
  post 'users/create' => 'users#create'
  post 'users/ajax' => 'users#ajax'
  get 'user/logout' => 'users#logout'

  resources :u, :only => [:show] do |u|
    member do
      match '/albums'=>'u#albums',:as=>'albums',:via=>[:get]
      match '/albums_upload'=>'u#albums_upload',:as=>'albums_upload',:via=>[:get,:post]
      match '/album/:aid' => 'u#album', :constraints => {:aid => /\d/}, :as => 'album_show',:via=>[:get]
    end
  end

  resources :places do
    member do
      get 'photos'
      post 'wantgoto'
      post 'beento'
    end
    collection do
      match 'city/:name' => 'places#city', :constraints => {:name => /[a-zA-z1-9]+/}, :as => 'city',:via=>:get
      match 'area/:name' => 'places#area', :constraints => {:name => /[a-zA-z1-9]+/}, :as => 'area',:via=>:get
    end
  end

  resources :photos do
    collection do
      post :upload
    end
  end

  resources :asks, :path => 'wenda'

  resources :guides

  resources :comments do
    collection do
      get 'list', :to => "comments#list",:as => 'list'
      get :show
      get :getone
    end
  end

  resources :forums,:except => [:show] do
    collection do
      resources :topics,:except => [:show] do
        collection do
          get 'post', :to => "topics#new",:as => 'post'
          get ':id', :to => "topics#show",:constraints => {:id => /[\d]+/},:as => 'show'
        end
      end
    end
  end

  root 'main#two', :as => 'main'

  get "admin" => 'admin#frame', :as => 'admin'
  post 'admin/login' => 'admin#login'
  namespace :admin do |admin|
    resources :ads
    resources :main
    resources :forums
    resources :places
    resources :users
    resources :options
    resources :comments
    resources :recommends
    resources :managers
    resources :guides
    resources :articles
  end

  match ':controller(/:action(/:id))(.:format)', :constraints => {:id => /[\d]+/}, :via => [:get]

end

app/models/topic.rb
#coding:utf-8
class Topic < ActiveRecord::Base
  #attr_accessible :subject_id, :title, :title_color, :user_id, :club_id, :comments_num, :activity_id, :forum_id, :hits_num, :is_comment, :is_fixed, :is_good, :is_recommend, :last_comment_time, :last_comment_user_id, :last_comment_user_name
  #attr_accessible :from_form, :content, :activity_data, :post_data, :together_data
  belongs_to :forum, :foreign_key => "forum_id"
  belongs_to :user
  belongs_to :subject_category, :foreign_key => "subject_id"
  belongs_to :reply_user, :class_name => "User", :foreign_key => "last_comment_user_id"

  has_one :activity
  has_one :together
  has_one :post

  #基本验证
  validates_presence_of :forum_id
  validates_presence_of :subject_id
  validates_presence_of :user_id
  #validates_length_of :title, :in => 2..60

  #保存验证
  validate do
    #来自保单操作
    if self[:from_form]
      if self.subject_id==1
        self.errors.add(:base, '作者不能为空') if self.user_id.blank?
        self.errors.add(:base, '标题不能为空') if self.title.blank?
        self.errors.add(:base, '标题字数不能少于3个字符') if (self.title.blank?)==false && self.title.size<3
        self.errors.add(:base, '内容不能为空') if self.content.blank?
        self.errors.add(:base, '内容字符至少10个字符') if (self.content.blank?)==false && self.content.size<10
      elsif self.subject_id==2
        self.errors.add(:base, '标题不能为空') if self.title.blank?
        self.errors.add(:base, '日期不能为空') if self.together_data['start_at'].blank?
        self.errors.add(:base, '详细说明不能为空') if self.content.blank?
      elsif self.subject_id==3
        self.errors.add(:base, '标题不能为空') if self.title.blank?
        self.errors.add(:base, '开始日期不能为空') if self.activity_data['start_at'].blank?
        self.errors.add(:base, '结束不能为空') if self.activity_data['finish_at'].blank?
        self.errors.add(:base, '活动地址不能为空') if self.activity_data['address'].blank?
        self.errors.add(:base, '详细说明不能为空') if self.content.blank?
      end
    end
  end

  #保存验证
  #before_save :topic_before_save

  #创建topic
  after_create :topic_after_create

  #belongs_to :forum,:touch=>true

  #查询基本字段
  scope :base_field, ->{select("topics.id,topics.title,topics.forum_id,topics.subject_id,topics.user_id,topics.title_color,topics.last_comment_user_id,topics.last_comment_time,topics.hits_num,topics.comments_num,topics.is_fixed,topics.is_good,topics.created_at")}

  #自定义详情字段
  def content
    @content
  end

  def content=(str)
    @content=str
  end

  #自定义话题字段
  def post_data
    @post_data
  end

  def post_data=(arr)
    @post_data=arr
  end

  #自定义活动字段
  def from_form
    @from_form
  end

  def from_form(boolean=false)
    @from_form=boolean
  end

  def together_data
    @together_data
  end

  def together_data=(arr)
    @together_data=arr
  end

  def activity_data
    @activity_data
  end

  def activity_data=(arr)
    @activity_data=arr
  end

  private

  #后续添加
  def topic_after_create
    if self.subject_id==1
      post=Post.new()
      post.topic_id=self.id
      post.content=@content
      post.save
    elsif self.subject_id==2
      together=Together.new
      together.topic_id=self.id
      together.address=self.together_data['address']
      together.start_at=self.together_data['start_at']
      together.finish_at=self.together_data['finish_at']
      together.content=@content
      together.save
    elsif self.subject_id==3
      activity=Activity.new
      activity.topic_id=self.id
      activity.address=self.activity_data['address']
      activity.start_at=self.activity_data['start_at']
      activity.finish_at=self.activity_data['finish_at']
      activity.content=@content
      activity.save
    end

  end


  #首页攻略
  def self.guides(limit=5)
    Topic.base_field.where(:subject_id=>4).includes(:user,:forum).order("topics.id DESC").limit(limit)
  end

  #首页活动
  def self.activities(limit=5)
    Topic.base_field.where(:subject_id=>3).includes(:user,:forum).order("topics.id DESC").limit(limit)
  end

  #热门话题
  def self.hot(limit=5,month_ago=1)
    begin_date=(month_ago).month.ago.to_s(:db)
    Topic.base_field.where(:subject_id=>1).where("topics.created_at>=?",begin_date).includes(:user).order("topics.comments_num DESC").limit(limit)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white show through.
    def topic_params
      params.require(:topic).permit(:forum_id, :subject_id, :title, :title_color, :user_id, :is_fixed, :is_good, :is_recommend, :hits_num, :comments_num, :last_comment_user_id, :last_comment_time)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :forum_id %><br>
    <%= f.number_field :forum_id %>
  </div>
  <div class="field">
    <%= f.label :subject_id %><br>
    <%= f.number_field :subject_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title_color %><br>
    <%= f.text_field :title_color %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :is_fixed %><br>
    <%= f.check_box :is_fixed %>
  </div>
  <div class="field">
    <%= f.label :is_good %><br>
    <%= f.check_box :is_good %>
  </div>
  <div class="field">
    <%= f.label :is_recommend %><br>
    <%= f.check_box :is_recommend %>
  </div>
  <div class="field">
    <%= f.label :hits_num %><br>
    <%= f.number_field :hits_num %>
  </div>
  <div class="field">
    <%= f.label :comments_num %><br>
    <%= f.number_field :comments_num %>
  </div>
  <div class="field">
    <%= f.label :last_comment_user_id %><br>
    <%= f.number_field :last_comment_user_id %>
  </div>
  <div class="field">
    <%= f.label :last_comment_time %><br>
    <%= f.datetime_select :last_comment_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/create.html.erb
<h1>Topics#create</h1>
<p>Find me in app/views/topics/create.html.erb</p>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Topics#index</h1>
<p>Find me in app/views/topics/index.html.erb</p>

app/views/topics/new.html.erb
<% content_for:head do %>
    <script type="text/javascript" charset="utf-8" src="/static/My97DatePicker/WdatePicker.js"></script>
    <script type="text/javascript" charset="utf-8" src="/static/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/static/ueditor/ueditor.all.js"></script>
<% end %>

<div class="qyer_head_crumbg">
  <div class="qyer_head_crumb">
    <a href="<%= main_path %>">首页</a>&nbsp;&gt;&nbsp;<a href="<%= forums_path %>">论坛</a><% if @forum %>&nbsp;&gt;&nbsp;<a href="<%= list_forums_path @forum.id %>"><%= @forum[:name] %></a><% end %>&nbsp;&gt;&nbsp;发新话题
  </div>
</div>

<%= block_alert @topic %>
<% @topic.forum_id=params[:fid] %>
<form action="<%= topics_path %>" id="forum_form" style="margin:10px 0" method="post">

  <input type="hidden" name="topic[forum_id]" value="<%= @topic.forum_id %>"/>
  <ul class="base_tab" style="margin:10px 0">
    <li><a href="javascript:;" class="cur" sid="1">话题</a></li>
    <li><a href="javascript:;" sid="2">约伴</a></li>
    <li><a href="javascript:;" sid="3">活动</a></li>
    <li><a href="javascript:;" sid="4">游击</a></li>
    <li><a href="javascript:;" sid="5">比赛</a></li>
  </ul>

  <ul>
    <li><label>标题：</label><input name="topic[title]" id="form_title" type="text" class="ui_input" style="width:700px"/>&nbsp;&nbsp;&nbsp;<span class="required">*</span></li>
  </ul>

  <ul id="subject1" subject="topic" >
  </ul>

  <ul id="subject2" subject="together" style="display:none">
    <li>
      <label>日期：</label><input name="topic[together_data][start_at]" type="text" class="ui_input ui_input_calendar" style="width:340px;margin-right: 10px" onClick="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:00',skin:'twoer'})"/><input name="topic[together_data][finish_at]" type="text" class="ui_input ui_input_calendar" style="width:340px;margin-right: 10px" onClick="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:00',skin:'twoer'})"/>&nbsp;&nbsp;&nbsp;<span class="required">*</span>
    </li>
    <li>
      <label>目的地：</label><input name="topic[together_data][address]" type="text" class="ui_input ui_input_address" style="width:700px"/>&nbsp;&nbsp;&nbsp;<span style="color:#999">可选，多个请用空格隔开</span>
    </li>
  </ul>

  <ul id="subject3" subject="activity" style="display:none">
    <li>
      <label>日期：</label><input name="topic[activity_data][start_at]" type="text" class="ui_input ui_input_calendar" style="width:340px;margin-right: 10px" onClick="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:00',skin:'twoer'})"/><input name="topic[activity_data][finish_at]" type="text" class="ui_input ui_input_calendar" style="width:340px;margin-right: 10px" onClick="WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:00',skin:'twoer'})"/><span class="required">*</span>
    </li>
    <li>
      <label>地址：</label><input name="topic[activity_data][address]" type="text" class="ui_input ui_input_address" style="width:700px"/>&nbsp;&nbsp;&nbsp;<span style="color:#999">填写活动地址或目的地</span>
    </li>
    <li>
      <label>名额：</label><input name="topic[activity_data][sign_limit]" type="text" class="ui_input ui_input_address" style="width:700px"/>&nbsp;&nbsp;&nbsp;<span style="color:#999">填写活动名额，不填为不限</span>
    </li>
   </ul>

  <div style="height:370px">
    <textarea name="topic[content]" id="content" cols="30" rows="10" style="width:100%;height:300px"></textarea>
    <%= render 'global/ueditor', :id => 'content', :options => {:initialFrameHeight => '300'} %>
  </div>
  <input type="hidden" name="topic[subject_id]" id="subject_id" value="<%= @topic.subject_id %>"/>

  <button id="topic_submit_button" type="submit" class="btn btn-mint">立即发布</button>
</form>

<% content_for:script do %>
    <script type="text/javascript">
        seajs.use(['lib','forum/latest/forum'], function(lib,forum) {
            forum.changeSubject();
            $('#forum_form').bind("submit", function (e) {
                e.preventDefault();
                new lib.ajaxForm($(this), {
                    submitButton: 'topic_submit_button',
                    dataType: 'json'
                }).send();
            });
        });
    </script>
<% end %>

app/views/topics/show.html.erb
<% @title=@topic.title %>

<% content_for:style do %>
    <link rel="stylesheet" href="/css/forum/text.css"/>
    <link rel="stylesheet" href="/css/common/comments.css"/>
    <style type="text/css">
      #main_body{width: 90%}
    </style>
<% end %>

<% content_for:full_body do %>
    <div class="qyer_head_crumbg">
      <div class="qyer_head_crumb">
        <a href="<%= main_path %>">首页</a>&nbsp;&gt;&nbsp;<a href="<%= forums_path %>">论坛</a>&gt; <a href="<%= list_forums_path @topic.forum_id %>"><%= @topic.forum.name %></a> &nbsp;&gt;&nbsp;<%= @topic.title %>    </div>
    </div>

    <div class="bbs_titboxs">
      <div class="bbs_titbox">
        <h1 class="bbs_titbox_title fontYaHei qyer_spam_text_filter">经验分享：美国B1/B2签2个月的行政审理结束拿到签证有感</h1>

        <div class="bbs_titbox_info">


          <div class="infos">
            <img src="/avatar/up.jpeg" alt="zhaojiangang_" style="position:absolute;left:0;top:0">
            作者：<a href="<%= u_path @topic.user_id %>" class="ml10" ><%= @topic.user.username %></a>
            <br>
            发表于 <%= @topic.created_at.to_s(:db) %> <span class="ml15 mr15">|</span>
            <span class="views"><%= @topic.hits_num %></span>
            <span class="sum"><%= @topic.comments_num %></span>
            <span class="like">0</span>
          </div>

          <div class="fr">
                <div id="bbs_tools" class="bbs_tools" style="position: relative;top: 0px;background:#fff">
                  <a href="javascript:;" id="share" class="share" rel="nofollow" data-bn-ipg="22">分享</a>
                  <a href="javascript:;" class="collect" rel="nofollow" data-bn-ipg="21">收藏</a>
                  <a id="recommend_add" style="" data-tid="837722" href="misc.php?action=recommend&amp;do=add&amp;tid=837722" onclick="if(QYER.uid&gt;0){ajaxmenu(this, 3000, 1, 0, '43', 'recommendupdate(1)');}else{ajaxlogin(0,'','bbsajax.php','pagereload');};doane(event);" class="like" rel="nofollow" data-bn-ipg="20">喜欢</a>
                </div>
          </div>

        </div>
      </div>
    </div>

<% end %>

<div>

<div class="bbs_main">

      <div class="bbs_txtbox" >
        <% if @topic.post %>
        <%=raw @topic.post.content %>
        <% end %>
      </div>
<div>
  分类：<a href="forum-3-62-1.html" class="category" >美洲国家签证</a>
</div>
  <%= comment_list :hidden_field => {:topic_id => @topic.id}, :query_param => {:topic_id => @topic.id} %>


</div>
<div class="bbs_sidebar">




  <!--右侧目的地-->
  <div class="mb20">
    <h3 class="bbs_txttit"><span class="fb f14">相关目的地</span></h3>
    <ul class="bbs_placelist clearfix">
      <li class="clearfix">
        <p class="bbs_placelist_pic"><a href="http://place.qyer.com/usa/" target="_blank" data-bn-ipg="24-1-1"><img src="/images/forum/48.jpg" width="48" height="48" alt="美国" title="美国"></a></p>

        <p class="bbs_placelist_title"><a href="http://place.qyer.com/usa/" title="美国 USA" target="_blank" data-bn-ipg="24-1-2">美国 USA</a></p>

        <p class="bbs_placelist_txt">景点&nbsp;<span class="fb">1268</span>&nbsp;&nbsp;&nbsp;&nbsp;照片&nbsp;<span class="fb">149213</span>&nbsp;&nbsp;&nbsp;&nbsp;问答&nbsp;<span class="fb">6581</span></p></li>
    </ul>
  </div>

  <!--右侧游记-->
  <div class="mb20">
    <h3 class="bbs_txttit"><span class="fb f14">相关游记帖</span></h3>
    <ul class="bbs_travellist">
      <li class="first"><p class="title"><a href="thread-269212-1.html" target="_blank" title="人生第二杆系列之-----88天环游美加----直播结束 账单出炉 补图ING  （电梯直达各楼）" data-bn-ipg="25-1-1">人生第二杆系列之-----88天环游美加----直播结束 账单出炉 补图ING （电梯直达各楼）</a></p>

        <p class="other"><span class="fr">回复 3577 | 查看 242960</span><a href="http://user.qyer.com/user_uid_368649" target="_blank" data-bn-ipg="25-1-2">来生</a></p></li>
      <li><p class="title"><a href="thread-707307-1.html" target="_blank" title="#美洲去野#买车自驾横穿美国3个月，从LA到KW,露营+MOTEL。" data-bn-ipg="25-2-1">#美洲去野#买车自驾横穿美国3个月，从LA到KW,露营+MOTEL。</a></p>

        <p class="other"><span class="fr">回复 614 | 查看 54696</span><a href="http://user.qyer.com/user_uid_1337055" target="_blank" data-bn-ipg="25-2-2">咏歌闪闪</a></p></li>
      <li><p class="title"><a href="thread-756524-1.html" target="_blank" title="38天，17,000元，坐巴士穷游美加" data-bn-ipg="25-3-1">38天，17,000元，坐巴士穷游美加</a></p>

        <p class="other"><span class="fr">回复 354 | 查看 40900</span><a href="http://user.qyer.com/user_uid_326962" target="_blank" data-bn-ipg="25-3-2">wxm1949</a></p></li>
      <li><p class="title"><a href="thread-495312-1.html" target="_blank" title="160天环游美国   我的第一个长篇 （全文完 电梯2楼 感谢所有的朋友 再见）" data-bn-ipg="25-4-1">160天环游美国 我的第一个长篇 （全文完 电梯2楼 感谢所有的朋友 再见）</a></p>

        <p class="other"><span class="fr">回复 800 | 查看 362998</span><a href="http://user.qyer.com/user_uid_1104629" target="_blank" data-bn-ipg="25-4-2">loyata</a></p></li>
      <li><p class="title"><a href="thread-286122-1.html" target="_blank" title="行色美国-30天从美西到美东（15万文字，850幅图片，电梯首页，新增美国签经，全文完)" data-bn-ipg="25-5-1">行色美国-30天从美西到美东（15万文字，850幅图片，电梯首页，新增美国签经，全文完)</a></p>

        <p class="other"><span class="fr">回复 508 | 查看 134451</span><a href="http://user.qyer.com/user_uid_128307" target="_blank" data-bn-ipg="25-5-2">kathyli</a></p></li>
    </ul>
  </div>

  <div class="bbs_txttag_box mb10">
    <h3 class="bbs_txttit"><span class="fb f14">标签</span></h3>

    <div class="bbs_txttag_list">
      <a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a><a href="#" class="ask_tag"><strong class="ask_tag_strong">尼泊尔</strong></a>
    </div>
  </div>


</div>
<div class="cb"></div>
</div>

<% content_for:script do %>
    <script type="text/javascript">
        seajs.use(['lib','forum/latest/forum'], function(lib,forum) {
            forum.floatTool();
            $('#forum_form').bind("submit", function (e) {
                e.preventDefault();
            });
        });
    </script>
<% end %>

app/views/topics/show2.html.erb
<% @title=@topic.title %>

<% content_for:style do %>
    <style type="text/css">
        #mainss_body {width: 95%;min-height:300px;margin:0 auto;}
        .qyesr_head_crumb{width:99%}
    </style>
<% end %>

<% content_for:head do %>
    <script type="text/javascript" charset="utf-8" src="/static/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/static/ueditor/ueditor.all.js"></script>
<% end %>



    <div class="qyer_head_crumbg">
      <div class="qyer_head_crumb">
        <a href="<%= main_path %>">首页</a>&nbsp;&gt;&nbsp;<a href="<%= forums_path %>">论坛</a>&gt; <a href="<%= list_forums_path @topic.forum_id %>"><%= @topic.forum.name %></a> &nbsp;&gt;&nbsp;<%= @topic.title %>    </div>
    </div>

<div style="text-align:right;margin-bottom:10px">
  <a class="btn btn-orange" href="javascript:;" id="comment_form_position"><span class="icon-comment"></span> 发表评论</a>
  <a class="btn btn-blue" href="javascript:;" data-href="/forums/topics/post?fid=<%=@topic.forum_id %>" id="new_topic_button"><span class="icon-plus"></span> 发表新帖</a>
</div>


<table class="view_table">

  <tr class="topic_info">
    <td class="hit_num" >查看：<%= @topic.hits_num %> 回复：<%= @topic.comments_num %></td>
    <td class="title"><h1>主题：<%= @topic.title %></h1>
    </td>
  </tr>

  <tr>
    <td class="user_info">
      <a href="sdf">seeyoup</a>
      <img src="/avatar/1_o.jpg" width="80" height="80" alt="zhaojiangang_">
    </td>
    <td class="view_content">
      <div class="infos" style="color:#999;font-size:12px;border-bottom:1px dashed #eee;padding:7px 0">
        <span style="color:#f60;font-weight:bold">楼主</span> 发表于 <%= @topic.created_at.to_s(:db) %>
      </div>
      <div style="line-height:1.7em;font-size:14px;padding:10px 15px 100px 15px;font-family: verdana">
        <% if @topic.post %>
            <%= raw @topic.post.content %>
        <% elsif @topic.together %>
            <%= raw @topic.together.content %>
        <% elsif @topic.activity %>
            <%= raw @topic.activity.content %>
        <% end %>
      </div>

      <div class="view_tools" >ffffffff</div>
      <div class="signatures" ><span class="icon-pencil"></span>&nbsp;<%= @topic.user.signatures %></div>

    </td>
  </tr>
</table>

<%= comment_list :hidden_field => {:topic_id => @topic.id}, :query_param => {:topic_id => @topic.id,:topic=>true} %>

<% content_for:seajs_global do %>
global.logged_button('new_topic_button');
global.scroll_to_position('#comment_form_position','#cmt_submit_button');
<% end %>

app/views/topics/update.html.erb
<h1>Topics#update</h1>
<p>Find me in app/views/topics/update.html.erb</p>