config/routes.rb
Rails.application.routes.draw do

  get "install/setting"
  get "install/user"
  get "install/setcity"

  get "v2"=>'main#index'

  resources :forums
  resources :topics
  resources :logs

  resources :provinces
  resources :routes
  resources :asks, :path => 'wenda'

  match 'login' => 'users#login', :as => 'login', :via => [:get, :post]
  match 'register' => 'users#register', :as => 'register', :via => [:get, :post]
  post 'users/create' => 'users#create'
  post 'users/ajax' => 'users#ajax'
  get 'user/logout' => 'users#logout'

  resources :u, :only => [:show] do |u|
    member do
      match '/albums'=>'u#albums',:as=>'albums',:via=>[:get]
      match '/albums_upload'=>'u#albums_upload',:as=>'albums_upload',:via=>[:get,:post]
      match '/album/:aid' => 'u#album', :constraints => {:aid => /\d/}, :as => 'album_show',:via=>[:get]
    end
  end

  resources :places do
    member do
      get 'photos'
      post 'wantgoto'
      post 'beento'
    end
    collection do
      match 'city/:name' => 'places#city', :constraints => {:name => /[a-zA-z1-9]+/}, :as => 'city',:via=>:get
      match 'area/:name' => 'places#area', :constraints => {:name => /[a-zA-z1-9]+/}, :as => 'area',:via=>:get
    end
  end

  resources :photos do
    collection do
      post :upload
    end
  end

  resources :asks, :path => 'wenda'

  resources :guides

  resources :comments do
    collection do
      get 'list', :to => "comments#list",:as => 'list'
      get :show
      get :getone
    end
  end

  resources :forums,:except => [:show] do
    collection do
      resources :topics,:except => [:show] do
        collection do
          get 'post', :to => "topics#new",:as => 'post'
          get ':id', :to => "topics#show",:constraints => {:id => /[\d]+/},:as => 'show'
        end
      end
    end
  end

  root 'main#two', :as => 'main'

  get "admin" => 'admin#frame', :as => 'admin'
  post 'admin/login' => 'admin#login'
  namespace :admin do |admin|
    resources :ads
    resources :main
    resources :forums
    resources :places
    resources :users
    resources :options
    resources :comments
    resources :recommends
    resources :managers
    resources :guides
    resources :articles
  end

  match ':controller(/:action(/:id))(.:format)', :constraints => {:id => /[\d]+/}, :via => [:get]

end

app/models/place.rb
#coding: utf-8
#rails g  migration  add_fieldone_to_place tags:string category_id:integer img_path:string banner_path:string
class Place < ActiveRecord::Base
  #有这个字段的不管什么时候都有用id排序,很讨厌
  #default_scope :order => 'id'
  #字段白名单，可以通过parrt[:place]
  #会影响rake db:seed数据导入
  #attr_accessible相当于是白名单，定义哪些属性可以被mass assignment（大量赋值）
  #attr_accessible :name, :content, :tags, :category_id, :img_path, :img_ids, :province_id, :city_id, :area_id, :address, :is_recommended,:is_fixed, :interested_num, :favorites_num, :hits_num, :good_num, :intro, :content, :user_id,:wantgoto_num,:beengo_num

  #黑名单
  #
  #attr_protected :is_recommended, :interested_num, :favorites_num, :hits_num, :good_num

  #不允许为空
  validates_presence_of :content, :message => '不能为空'
  validates_presence_of :address, :text => '地址'
  validates_presence_of :intro, :text => '简介'
  validates_length_of :name, :in => (2..30), :message => '不能少于2个字符'
  validates_length_of :intro, :maximum => 250
  validates_presence_of :province_id, :text => '省份'
  validates_presence_of :city_id, :text => '所在地区'


  #validates_format_of :name, :with => /^[\w\.]+$/,
  #一般查询预览字段
  scope :base_field, -> { select("places.id,places.name,places.img_path,places.rating") }
  #范围快捷设置
  scope :recommended, -> { where(:is_recommended => true) }
  #用户信息
  scope :join_user, -> { select("users.username").joins("LEFT JOIN users ON users.id=places.user_id") }
  #地址位置信息
  scope :join_city, -> { select("provinces.name,cities.name").joins("LEFT JOIN provinces ON provinces.id=places.province_id LEFT JOIN cities ON cities.id=places.city_id") }
  #查询
  #scope :search, lambda { |k, a| where('places.name like ? OR places.name like ?', "%#{k}%", "%#{a}%") }
  scope :search, ->(k, a) { where('places.name like ? OR places.name like ?', "%#{k}%", "%#{a}%") }

  #热门目的地
  scope :hot, -> { order('hits_num DESC') }

  #自动创建一个相册
  after_create :create_album
  after_update :update_album

  #rails3写法
  #default_scope :order => '`places`.id DESC'

  #rails4写法
  #default_scope { where(color: 'red') }
  default_scope { order('`places`.id DESC') }

  #还可以这样追加model的方法
  def self.fixed
    where(:is_fixed => true)
  end

  #学习笔记
  #不验证
  #Place.save(:validate => false)

  belongs_to :user
  belongs_to :province
  belongs_to :city
  has_many :comments
  has_many :been_to_places
  has_many :want_to_places
  has_many :albums

  #获取目的地总数
  def self.getCount()
    Place.count()
  end

  #获取记录
  def self.get(*args)
    options = args.extract_options!
    puts "Arguments:  #{args.inspect}"
    puts "Options:    #{options.inspect}"
    get(1, 2)
    get(1, 2, :a => :b)
  end

  #推荐目的地
  def self.get_recommended(limit=6, options={})
    def_opt={:select => 'id,name,img_path,beengo_num,province_id,city_id', :where => ["is_recommended=?", true], :order => 'id DESC'}
    opt=def_opt.merge! options
    Place.select(opt[:select]).where(opt[:where]).includes(:province, :city).limit(limit).order(opt[:order])
  end

  private

  #创建新相册并保存图片
  def create_album
    album=Album.new
    album.name=self.name+'相册'
    album.place_id=self.id
    album.order_num=1
    album.cover_path=self.img_path if self.img_path
    if album.save && self.img_ids
      Photo.where(:id => img_ids.split(/,/)).update_all(:album_id => album.id)
    end
  end

  def update_album
    if self.img_ids && self.img_ids
      album=Album.find_or_create_by(:place_id => self.id, :name => self.name+'相册', :order_num => 1, :cover_path => self.img_path)
      album.update_attributes(:cover_path => self.img_path)
      if self.img_ids
        Photo.where(:id => img_ids.split(/,/)).update_all(:album_id => album.id)
      end
    end
  end


end

app/controllers/admin/places_controller.rb
#coding: utf-8
class Admin::PlacesController < AdminController

  #目的地列表
  def index
    conditions=Array.new
    if params[:q]
      conditions << "name LIKE ?"
      conditions << "%#{params[:q]}%"
    end
    @places=Place.where(conditions).includes([:user,:comments]).paginate(:page => params[:page], :per_page => 10)
  end

  #添加记录
  def new
    @place = Place.new
    @place[:user_id]=1
  end

  #编辑记录
  def edit
    @place = Place.find(params[:id])
    @album=Album.find_or_create_by_place_id(@place.id, :place_id => @place.id,:name=>@place.name+'相册',:order_num=>1)
    @pics=Photo.where(:album_id => @album.id)
  end

  #提交新建

  def create

    @place = Place.new(place_params)
    @place.is_fixed=params[:is_fixed]
    @place.is_recommended=params[:is_recommended]
    if @place.save
      respond :redirect_to => admin_places_path, :success => '目的地添加成功'
    else
      respond :action => 'new',:error => @place.errors.full_messages
    end
  end

  #显示
  def show
  end

  #保存修改
  def update

    @place = Place.find(params[:id])
    @place.is_fixed=params[:is_fixed]
    @place.is_recommended=params[:is_recommended]
    if @place.update_attributes(place_params)
      respond :redirect_to => admin_places_path, :success => '资料修改成功'
    else
      respond :action => 'edit', :error => @place.errors.full_messages
    end
  end

  #删除
  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    respond :redirect_to => admin_places_path, :success => '资料删除成功'
  end

  private

  def place_params
    params.require(:place).permit(:name, :content, :tags, :category_id, :img_path, :img_ids, :province_id, :city_id, :area_id, :address, :is_recommended,:is_fixed, :interested_num, :favorites_num, :hits_num, :good_num, :intro, :content, :user_id,:wantgoto_num,:beengo_num)
  end

end

app/controllers/places_controller.rb
#coding: utf-8
class PlacesController < ApplicationController

  def index

    @recommended=Rails.cache.fetch('place_home_recommendeds', :expires_in => 30.minutes) do
      Place.get_recommended(6)
    end

    @places = Place.order(:id=>:asc).includes(:province,:city,:comments).paginate(:page => params[:page], :per_page => 12)

    @provinces=Array.new
    Province.group.each_with_index do |p,key|
      @provinces[key]=Province.where(:group => key).includes(:cities)
    end

    respond_to do |format|
      format.html
      format.json { render json: @places }
    end
  end

  #按省份查看
  def area
    @name=params[:name]
    @province=not_found do
      Province.find_by_pinyin(@name)
    end
    @hot_city=City.select("cities.id,cities.name,cities.pinyin,(select count(places.id) from places where places.city_id=cities.id) as places_count").where("cities.province_id=?",@province.id).order("places_count DESC").limit(10)
  end

  #按城市查看
  def city
    @name=params[:name]
    @city=not_found do
      City.find_by_pinyin(@name)
    end
    @hot_place=Place.base_field.hot.limit(6)
  end

  #显示目的地
  def show
    @place=Place.find(params[:id])
    @place.hits_num=@place.hits_num+1
    @place.save()
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
      format.xml { render xml: @place }
    end
  end


  #相册
  def photos
    @place=Place.find(params[:id])
    @album=Album.find_or_create_by(:place_id => @place.id, :name => @place.name+'相册')
    @photos=Photo.where(:album_id=>@album.id).order(:id=>:desc).includes(:usre).paginate(:page => params[:page], :per_page =>20)
  end

  #添加记录
  def new
    @place = Place.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end

    Mail.new({:to => 'mikel@test.lindsaar.net',
              'from' => 'bob@test.lindsaar.net',
              :subject => 'This is an email',
              :body => 'This is the body'})

  end

  #增加去过人数
  def wantgoto

    if logged_in?
      @want=WantToPlace.where(:place_id => params[:id], :user_id => current_uid)
      if @want.blank?
        WantToPlace.create(:place_id => params[:id], :user_id => current_uid)
      end
    end

    @place = Place.find(params[:id])
    if @place.update_attributes(:wantgoto_num => @place.wantgoto_num.to_i+1)
      respond :_format => 'json', :wantgoto_num => @place.wantgoto_num, :beengo_num => @place.beengo_num
    end
  end

  #增加去过人数
  def beento

    if logged_in?
      @been=BeenToPlace.where(:place_id => params[:id], :user_id => current_uid)
      if @been.blank?
        BeenToPlace.create(:place_id => params[:id], :user_id => current_uid)
      end
    end
    @place = Place.find(params[:id])
    if @place.update_attributes(:beengo_num => @place[:beengo_num].to_i+1)
      respond :_format => 'json', :wantgoto_num => @place.wantgoto_num, :beengo_num => @place.beengo_num
    end
  end

end

app/controllers/user/places_controller.rb
#coding: utf-8
#会员
class User::PlacesController < User::UcenterController

  def index
    render :text => 'nothing'
  end

  def new
    render :text=>'post'
  end


end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/places/_form.html.erb
<% content_for:head do %>
    <link rel="stylesheet" type="text/css" href="/static/uploadify/uploadify.css">
    <script type="text/javascript" src="/static/uploadify/jquery.uploadify-3.1.min.js"></script>
    <script type="text/javascript" charset="utf-8" src="/static/ueditor/ueditor.config.js"></script>
    <script type="text/javascript" charset="utf-8" src="/static/ueditor/ueditor.all.js"></script>
<% end %>

<%
   if @place.new_record?
     method_path=admin_places_path
   else
     method_path=admin_place_path(@place.id)
   end
%>

<%= form_for(@place, :url => method_path, :html => {:id => 'form1', :class => 'form-horizontal'}) do |f| %>

    <%= block_alert @place %>

    <div class="control-group">
      <%= f.label :name, '自定义标题', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :province_id, :class => 'control-label' %>
      <div class="controls">
        <%= province_city_area_select :place, @place.province_id, @place.city_id, @place.area_id %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :address, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :user_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :user_id, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :tags, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :tags, :class => 'input-xxlarge' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :intro, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :intro, :rows => '3', :class => 'span10' %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :content, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :content, :rows => '6', :id => 'content', :class => 'span10' %>
        <%= render 'global/ueditor', :id => 'content', :options => {:initialFrameHeight => '250'} %>
      </div>
    </div>



    <div class="control-group" id="uploadify_preview" style="display:<%= (@pics.blank?) ? 'none' : 'block' %>">
      <div class="controls">
        <ul>
          <% if @pics %>
              <% @pics.each do |p| %>
                  <li><img src="<%= p.img_path %>" alt=""/></li>
              <% end %>
          <% end %>
          <li id="includBefore" style="display: none"></li>
        </ul>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.hidden_field :img_ids, :class => 'input-xxlarge', :id => "img_ids" %>
        <%= f.hidden_field :img_path, :class => 'input-xxlarge', :id => "img_path" %>
        <input type="file" name="file_upload" id="file_upload"/>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :is_recommended, :class => 'control-label' %>

      <div class="controls">
        <label class="checkbox inline">
          <input type="checkbox" name="is_recommended" <%= 'checked' if @place.is_recommended %> > 推荐
        </label>

        <label class="checkbox inline">
        <input type="checkbox" name="is_fixed" <%= 'checked' if @place.is_fixed %>> 置顶
        </label>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <%= f.button :class => "btn btn-primary", :id => 'submit_button' %>
        <button type="button" class="btn" id="cancel_button" onclick="history.back()">取消</button>
      </div>
    </div>
<% end %>

<script type="text/javascript">
    readyScript.bind = function () {
        $('#form1').bind("submit", function (e) {
            e.preventDefault();
            new ajaxForm($(this), {
                dataType: 'json'
            }).send();
        });
        var uploader = new go_uploader();
        uploader.preview();
        uploader.uploadify();
    }
</script>

app/views/admin/places/edit.html.erb
<div class="container-fluid">
  <div class="row-fluid">

    <div class="area-top clearfix">
      <div class="pull-left header">
        <h3 class="title">
          <i class="icon-edit"></i>
          编辑<%= t("activerecord.models.place") %>
        </h3>
        <h5>
          t("admin.event") t(:event, :scope => :admin )
          <%= Time.now %>
        </h5>
      </div>

    </div>
  </div>
</div>


<div class="container-fluid padded">


  <div class="row-fluid">
    <div class="span12">

      <div class="box">
        <div class="box-header">
          <span class="title"><i class="icon-warning-sign"></i> 修改记录</span>
        </div>

        <div class="box-content">
          <div class="container-fluid padded">
            <div class="row-fluid">
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/admin/places/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="area-top clearfix">
      <div class="pull-left header">
        <h3 class="title">
          <i class="icon-flag"></i>
          <%= I18n.t 'activerecord.models.place' %>
        </h3>
        <h5>
          <% if local_assigns.has_key? :headline %>
              Headline: <%= headline %>
          <% else %>
              Headline not defined
          <% end %>
          <%= request.fullpath %>
          <%= request.protocol %>--<%= request.host_with_port %><br>
        </h5>
      </div>
    </div>
  </div>
</div>

<div class="container-fluid padded">
  <div class="row-fluid">
    <%= block_alert %>
    <div class="box">
      <div class="box-header">
        <span class="title"><i class="icon-list"></i>&nbsp;所有记录</span>
        <ul class="box-toolbar">
          <li>
            <form class="fill-up" style="width:200px">
              <label class="input-with-submit">
                <input name="q" type="text" placeholder="Search...">
                <button type="submit" class="submit-icon">
                  <i class="icon-search"></i>
                </button>
              </label>
            </form>
          </li>


          <li class="toolbar-link">
            <a href="#" data-toggle="dropdown"><i class="icon-cog"></i></a>
            <ul class="dropdown-menu">
              <li><a href="<%= new_admin_place_path %>"><i class="icon-plus-sign"></i> Add</a></li>
              <li><a href="#"><i class="icon-remove-sign"></i> Remove</a></li>
              <li><a href="#"><i class="icon-pencil"></i> Edit</a></li>
            </ul>
          </li>
        </ul>
      </div>

      <div class="box-content">
        <table class="table table-normal" id="record_table">
          <thead>
          <tr>
            <td class="record-checkbox">审核</td>
            <td class="record-title">标题</td>
            <td class="record-cmthit">评论/点击</td>
            <td class="record-cmthit">想去/去过</td>
            <td class="record-author">作者</td>
            <td class="record-date">发布日期</td>
            <td class="record-operate">操作</td>
          </tr>
          </thead>

          <tbody>

          <% @places.each do |r| %>
              <tr id="record_<%= r.id %>">
                <td class="record-checkbox"><input type="checkbox" name="cid[]" value="1"></td>
                <td class="record-title"><a href="<%= edit_admin_place_path(r, :format => 'html') %>"><%= r.name %></a></td>
                <td class="record-cmthit"><span><%= r.comments.size %></span>/<%= r.hits_num %></td>
                <td class="record-cmthit"><%= r.wantgoto_num.to_i %>/<%= r.beengo_num.to_i %></td>
                <td class="record-author"><%= r.user.username if r.user %></td>
                <td class="record-date"><%= to_pretty(r.created_at) %>
                  <% r.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
                <td class="record-operate">
                  <a href="<%= place_path(r) %>" target="_blank"><i class="icon-search"></i></a>
                  <a href="<%= edit_admin_place_path(r) %>"><i class="icon-edit"></i></a>
                  <a href="javascript:;"><i class="icon-remove" cid="<%= r.id %>"></i></a>
                </td>
              </tr>
          <% end %>

          </tbody>
        </table>

        <% unless @places.blank? %>
        <div class="table-footer">
          <div class="dataTables_info" id="DataTables_Table_0_info"></div>
          <%= go_pager @places %>
        </div>
        <% else %>
        <div>暂时还没有记录。</div>
        <% end %>

      </div>
    </div>
  </div>

</div>
<script type="text/javascript">
    readyScript.bind = function () {
        $("#record_table .icon-remove").each(function () {
            $(this).bind("click", function () {
                var cid=$(this).attr('cid');
                new candyLayer().deleteRecord(cid,{
                    url:'/admin/places/'+cid
                });
            });
        });
    }
</script>

app/views/admin/places/new.html.erb
<div class="container-fluid">
  <div class="row-fluid">

    <div class="area-top clearfix">
      <div class="pull-left header">
        <h3 class="title">
          <i class="icon-edit"></i>
          Form Elements
        </h3>
        <h5>
          A subtitle can be added here
        </h5>
      </div>

    </div>
  </div>
</div>


<div class="container-fluid padded">


  <div class="row-fluid">
    <div class="span12">

      <div class="box">
        <div class="box-header">
          <span class="title"><i class="icon-warning-sign"></i> Forms with validation</span>
        </div>

        <div class="box-content">
          <div class="container-fluid padded">
            <div class="row-fluid">
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/admin/places/show.html.erb
<h1>Admin::Places#show</h1>
<p>Find me in app/views/admin/places/show.html.erb</p>

app/views/admin/places/upload.html.erb
<h1>Admin::Places#upload</h1>
<p>Find me in app/views/admin/places/upload.html.erb</p>