config/routes.rb
Rails.application.routes.draw do

  get "install/setting"
  get "install/user"
  get "install/setcity"

  get "v2"=>'main#index'

  resources :forums
  resources :topics
  resources :logs

  resources :provinces
  resources :routes
  resources :asks, :path => 'wenda'

  match 'login' => 'users#login', :as => 'login', :via => [:get, :post]
  match 'register' => 'users#register', :as => 'register', :via => [:get, :post]
  post 'users/create' => 'users#create'
  post 'users/ajax' => 'users#ajax'
  get 'user/logout' => 'users#logout'

  resources :u, :only => [:show] do |u|
    member do
      match '/albums'=>'u#albums',:as=>'albums',:via=>[:get]
      match '/albums_upload'=>'u#albums_upload',:as=>'albums_upload',:via=>[:get,:post]
      match '/album/:aid' => 'u#album', :constraints => {:aid => /\d/}, :as => 'album_show',:via=>[:get]
    end
  end

  resources :places do
    member do
      get 'photos'
      post 'wantgoto'
      post 'beento'
    end
    collection do
      match 'city/:name' => 'places#city', :constraints => {:name => /[a-zA-z1-9]+/}, :as => 'city',:via=>:get
      match 'area/:name' => 'places#area', :constraints => {:name => /[a-zA-z1-9]+/}, :as => 'area',:via=>:get
    end
  end

  resources :photos do
    collection do
      post :upload
    end
  end

  resources :asks, :path => 'wenda'

  resources :guides

  resources :comments do
    collection do
      get 'list', :to => "comments#list",:as => 'list'
      get :show
      get :getone
    end
  end

  resources :forums,:except => [:show] do
    collection do
      resources :topics,:except => [:show] do
        collection do
          get 'post', :to => "topics#new",:as => 'post'
          get ':id', :to => "topics#show",:constraints => {:id => /[\d]+/},:as => 'show'
        end
      end
    end
  end

  root 'main#two', :as => 'main'

  get "admin" => 'admin#frame', :as => 'admin'
  post 'admin/login' => 'admin#login'
  namespace :admin do |admin|
    resources :ads
    resources :main
    resources :forums
    resources :places
    resources :users
    resources :options
    resources :comments
    resources :recommends
    resources :managers
    resources :guides
    resources :articles
  end

  match ':controller(/:action(/:id))(.:format)', :constraints => {:id => /[\d]+/}, :via => [:get]

end

app/models/place.rb
#coding: utf-8
#rails g  migration  add_fieldone_to_place tags:string category_id:integer img_path:string banner_path:string
class Place < ActiveRecord::Base
  #有这个字段的不管什么时候都有用id排序,很讨厌
  #default_scope :order => 'id'
  #字段白名单，可以通过parrt[:place]
  #会影响rake db:seed数据导入
  #attr_accessible相当于是白名单，定义哪些属性可以被mass assignment（大量赋值）
  #attr_accessible :name, :content, :tags, :category_id, :img_path, :img_ids, :province_id, :city_id, :area_id, :address, :is_recommended,:is_fixed, :interested_num, :favorites_num, :hits_num, :good_num, :intro, :content, :user_id,:wantgoto_num,:beengo_num

  #黑名单
  #
  #attr_protected :is_recommended, :interested_num, :favorites_num, :hits_num, :good_num

  #不允许为空
  validates_presence_of :content, :message => '不能为空'
  validates_presence_of :address, :text => '地址'
  validates_presence_of :intro, :text => '简介'
  validates_length_of :name, :in => (2..30), :message => '不能少于2个字符'
  validates_length_of :intro, :maximum => 250
  validates_presence_of :province_id, :text => '省份'
  validates_presence_of :city_id, :text => '所在地区'


  #validates_format_of :name, :with => /^[\w\.]+$/,
  #一般查询预览字段
  scope :base_field, -> { select("places.id,places.name,places.img_path,places.rating") }
  #范围快捷设置
  scope :recommended, -> { where(:is_recommended => true) }
  #用户信息
  scope :join_user, -> { select("users.username").joins("LEFT JOIN users ON users.id=places.user_id") }
  #地址位置信息
  scope :join_city, -> { select("provinces.name,cities.name").joins("LEFT JOIN provinces ON provinces.id=places.province_id LEFT JOIN cities ON cities.id=places.city_id") }
  #查询
  #scope :search, lambda { |k, a| where('places.name like ? OR places.name like ?', "%#{k}%", "%#{a}%") }
  scope :search, ->(k, a) { where('places.name like ? OR places.name like ?', "%#{k}%", "%#{a}%") }

  #热门目的地
  scope :hot, -> { order('hits_num DESC') }

  #自动创建一个相册
  after_create :create_album
  after_update :update_album

  #rails3写法
  #default_scope :order => '`places`.id DESC'

  #rails4写法
  #default_scope { where(color: 'red') }
  default_scope { order('`places`.id DESC') }

  #还可以这样追加model的方法
  def self.fixed
    where(:is_fixed => true)
  end

  #学习笔记
  #不验证
  #Place.save(:validate => false)

  belongs_to :user
  belongs_to :province
  belongs_to :city
  has_many :comments
  has_many :been_to_places
  has_many :want_to_places
  has_many :albums

  #获取目的地总数
  def self.getCount()
    Place.count()
  end

  #获取记录
  def self.get(*args)
    options = args.extract_options!
    puts "Arguments:  #{args.inspect}"
    puts "Options:    #{options.inspect}"
    get(1, 2)
    get(1, 2, :a => :b)
  end

  #推荐目的地
  def self.get_recommended(limit=6, options={})
    def_opt={:select => 'id,name,img_path,beengo_num,province_id,city_id', :where => ["is_recommended=?", true], :order => 'id DESC'}
    opt=def_opt.merge! options
    Place.select(opt[:select]).where(opt[:where]).includes(:province, :city).limit(limit).order(opt[:order])
  end

  private

  #创建新相册并保存图片
  def create_album
    album=Album.new
    album.name=self.name+'相册'
    album.place_id=self.id
    album.order_num=1
    album.cover_path=self.img_path if self.img_path
    if album.save && self.img_ids
      Photo.where(:id => img_ids.split(/,/)).update_all(:album_id => album.id)
    end
  end

  def update_album
    if self.img_ids && self.img_ids
      album=Album.find_or_create_by(:place_id => self.id, :name => self.name+'相册', :order_num => 1, :cover_path => self.img_path)
      album.update_attributes(:cover_path => self.img_path)
      if self.img_ids
        Photo.where(:id => img_ids.split(/,/)).update_all(:album_id => album.id)
      end
    end
  end


end

app/controllers/admin/places_controller.rb
#coding: utf-8
class Admin::PlacesController < AdminController

  #目的地列表
  def index
    conditions=Array.new
    if params[:q]
      conditions << "name LIKE ?"
      conditions << "%#{params[:q]}%"
    end
    @places=Place.where(conditions).includes([:user,:comments]).paginate(:page => params[:page], :per_page => 10)
  end

  #添加记录
  def new
    @place = Place.new
    @place[:user_id]=1
  end

  #编辑记录
  def edit
    @place = Place.find(params[:id])
    @album=Album.find_or_create_by_place_id(@place.id, :place_id => @place.id,:name=>@place.name+'相册',:order_num=>1)
    @pics=Photo.where(:album_id => @album.id)
  end

  #提交新建

  def create

    @place = Place.new(place_params)
    @place.is_fixed=params[:is_fixed]
    @place.is_recommended=params[:is_recommended]
    if @place.save
      respond :redirect_to => admin_places_path, :success => '目的地添加成功'
    else
      respond :action => 'new',:error => @place.errors.full_messages
    end
  end

  #显示
  def show
  end

  #保存修改
  def update

    @place = Place.find(params[:id])
    @place.is_fixed=params[:is_fixed]
    @place.is_recommended=params[:is_recommended]
    if @place.update_attributes(place_params)
      respond :redirect_to => admin_places_path, :success => '资料修改成功'
    else
      respond :action => 'edit', :error => @place.errors.full_messages
    end
  end

  #删除
  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    respond :redirect_to => admin_places_path, :success => '资料删除成功'
  end

  private

  def place_params
    params.require(:place).permit(:name, :content, :tags, :category_id, :img_path, :img_ids, :province_id, :city_id, :area_id, :address, :is_recommended,:is_fixed, :interested_num, :favorites_num, :hits_num, :good_num, :intro, :content, :user_id,:wantgoto_num,:beengo_num)
  end

end

app/controllers/places_controller.rb
#coding: utf-8
class PlacesController < ApplicationController

  def index

    @recommended=Rails.cache.fetch('place_home_recommendeds', :expires_in => 30.minutes) do
      Place.get_recommended(6)
    end

    @places = Place.order(:id=>:asc).includes(:province,:city,:comments).paginate(:page => params[:page], :per_page => 12)

    @provinces=Array.new
    Province.group.each_with_index do |p,key|
      @provinces[key]=Province.where(:group => key).includes(:cities)
    end

    respond_to do |format|
      format.html
      format.json { render json: @places }
    end
  end

  #按省份查看
  def area
    @name=params[:name]
    @province=not_found do
      Province.find_by_pinyin(@name)
    end
    @hot_city=City.select("cities.id,cities.name,cities.pinyin,(select count(places.id) from places where places.city_id=cities.id) as places_count").where("cities.province_id=?",@province.id).order("places_count DESC").limit(10)
  end

  #按城市查看
  def city
    @name=params[:name]
    @city=not_found do
      City.find_by_pinyin(@name)
    end
    @hot_place=Place.base_field.hot.limit(6)
  end

  #显示目的地
  def show
    @place=Place.find(params[:id])
    @place.hits_num=@place.hits_num+1
    @place.save()
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
      format.xml { render xml: @place }
    end
  end


  #相册
  def photos
    @place=Place.find(params[:id])
    @album=Album.find_or_create_by(:place_id => @place.id, :name => @place.name+'相册')
    @photos=Photo.where(:album_id=>@album.id).order(:id=>:desc).includes(:usre).paginate(:page => params[:page], :per_page =>20)
  end

  #添加记录
  def new
    @place = Place.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end

    Mail.new({:to => 'mikel@test.lindsaar.net',
              'from' => 'bob@test.lindsaar.net',
              :subject => 'This is an email',
              :body => 'This is the body'})

  end

  #增加去过人数
  def wantgoto

    if logged_in?
      @want=WantToPlace.where(:place_id => params[:id], :user_id => current_uid)
      if @want.blank?
        WantToPlace.create(:place_id => params[:id], :user_id => current_uid)
      end
    end

    @place = Place.find(params[:id])
    if @place.update_attributes(:wantgoto_num => @place.wantgoto_num.to_i+1)
      respond :_format => 'json', :wantgoto_num => @place.wantgoto_num, :beengo_num => @place.beengo_num
    end
  end

  #增加去过人数
  def beento

    if logged_in?
      @been=BeenToPlace.where(:place_id => params[:id], :user_id => current_uid)
      if @been.blank?
        BeenToPlace.create(:place_id => params[:id], :user_id => current_uid)
      end
    end
    @place = Place.find(params[:id])
    if @place.update_attributes(:beengo_num => @place[:beengo_num].to_i+1)
      respond :_format => 'json', :wantgoto_num => @place.wantgoto_num, :beengo_num => @place.beengo_num
    end
  end

end

app/controllers/user/places_controller.rb
#coding: utf-8
#会员
class User::PlacesController < User::UcenterController

  def index
    render :text => 'nothing'
  end

  def new
    render :text=>'post'
  end


end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_focus.html.erb
<div id="gui_focus" class="gui_focus fr">
  <div class="slides_container" style="overflow: hidden; position: relative; display: block;">
    <div class="slides_control" style="position: relative; width: 2280px; height: 360px; left: -760px;">
      <div style="position: absolute; top: 0px; left: 760px; z-index: 0; display: none;">
        <img src="/images/place/b7c4b6fdf7fda877c36e53b472d6aba9.jpg" alt=""/>
      </div>
      <div style="position: absolute; top: 0px; left: 760px; z-index: 0; display: none;">
        <img src="/images/place/436fb9c38b0f438dfe5e6707a7ba13ca.jpg" alt=""/>
      </div>
      <div style="position: absolute; top: 0px; left: 760px; z-index: 5; display: block;">
        <img src="/images/place/b7c4b6fdf7fda877c36e53b472d6aba9.jpg" alt=""/>
      </div>
      <div style="position: absolute; top: 0px; left: 760px; z-index: 0; display: none;">
        <img src="/images/place/d7476e342c2c3816aa7c4014ba094d0e.jpg" alt=""/>
      </div>
    </div>
  </div>
</div>

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
    <% if @place.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

          <ul>
            <% @place.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <br/>
      <%= f.text_field :name,:class=>'ui_input' %>
    </div>
    <div class="field">
      <%= f.label :img_path %>
      <br/>
      <%= f.text_field :img_path,:class=>'ui_input'  %>
    </div>
    <div class="field">
      <%= f.label :good_num %>
      <br/>
      <%= f.text_field :good_num,:class=>'ui_input'  %>
    </div>

    <div class="field">
      <%= f.label :been_num %>
      <br/>
      <%= f.text_field :been_num,:class=>'ui_input'  %>
    </div>

    <div class="field">
      <%= f.label :interested_num %>
      <br/>
      <%= f.text_field :interested_num,:class=>'ui_input'  %>
    </div>

    <div class="field">
      <%= f.label :favorites_num %>
      <br/>
      <%= f.text_field :favorites_num,:class=>'ui_input'  %>
    </div>
    <div class="field">
      <%= f.label :intro %>
      <br/>
      <%= f.text_field :intro,:class=>'ui_input'  %>
    </div>
    <div class="field">
      <%= f.label :content %>
      <br/>
      <%= f.text_area :content,:style=>'width:70%;height:300px' %>
    </div>
    <div class="field">
      <%= f.label :user_id %>
      <br/>
      <%= f.text_field :user_id,:class=>'ui_input'  %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/places/_index_right.html.erb
<div class="gui_all">
<h2 class="gui_title">全部穷游锦囊</h2>
<div class="ui_sort gui_tab">
  <a href="javascript:;" class="ui_sort_item ui_sort_item_current jsorderupdate" data-bn-ipg="20-1">按更新时间</a><span class="ui_sort_gap">|</span><a href="javascript:;" class="ui_sort_item jsorderdown" data-bn-ipg="20-2">最近7天下载量</a>
</div>
<div class="jsajaxshowpage">
<ul class="gui_jnlist clearfix">
  <% @places.each do |p| %>
      <li class="gui_jnlist_item">
        <div class="gui_jnlist_item_pic">
          <% img_path=(p.img_path.nil?)?'/images/default_img_thumb.png':p.img_path %>
          <a href="<%= place_path p %>" target="_blank" ><%=image_tag(img_path,{:width=>'130px',:height=>'90px',:alt=>p.name})%></a>
        </div>
        <p class="gui_jnlist_item_tit"><%=link_to truncate(p.name,:lenght=>6),p,{:target => '_blank'}%></p>
        <p class="gui_jnlist_item_text"><%= p.city.name %><br> <%= localize p.created_at,:format => :default %>更新</p>
      </li>
  <% end %>
</ul>

<%= go_pager @places %>

<div class="cb"></div>
</div>
<div class="cb"></div>
</div>

app/views/places/_recommended.html.erb
<div class="gui_news">
  <div class="ui_sort">
    <a href="javascript:;" class="ui_sort_item ui_sort_item_current jsrecommcon" type="1" data-bn-ipg="7-1">编辑推荐</a><span class="ui_sort_gap">|</span><a href="javascript:;" class="ui_sort_item jsrecommcon" type="0" data-bn-ipg="7-2">当季热门</a>
  </div>
  <ul class="gui_jnlist clearfix jsrecommcontent">

        <% @recommended.each do |p| %>
            <li class="gui_jnlist_item gui_jnlist_item_first">
              <div class="gui_jnlist_item_pic">
                <a href="/places/<%= p.id %>" target="_blank"><img src="<%= p.img_path %>" alt="<%= p.name %>" title="<%= p.name %>" width="130" height="90px"></a>
                <span class="new"></span>
              </div>
              <p class="gui_jnlist_item_tit"><%= link_to p.name, p, {:target => '_blank'} %></p>

              <p class="gui_jnlist_item_text"><%= p.city.name %><br><span class="sum"><%= p.beengo_num.to_i.to_s %></span>人去过</p>
            </li>
        <% end %>
  </ul>
</div>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<% content_for:style do %>
    <link rel="stylesheet" href="/css/place/style201209.css"/>
<% end %>

<div class="qyer_head_crumbg">
  <div class="qyer_head_crumb">
    <span class="text"><%= link_to '首页', main_path %></span>
    <span class="space">&gt;</span>

    <h1 class="current">目的地</h1>
  </div>
</div>


<div class="main">
  <div class="gui_top">
    <img src="/images/place/jn_title.png" width="960" height="72" alt="穷游锦囊">
  </div>
  <div class="clearfix pr">
    <!--目的地导航开始-->
    <%= render 'navbox' %>
    <!--结束-->
    <!--幻灯片开始-->
    <%= render 'focus' %>
    <!--结束-->
  </div>
  <div class="clearfix mt30">
    <%= render 'recommended' %>
  </div>
  <div class="clearfix mt30">
    <div class="aside fl">
      <%= render 'index_sidebar' %>
    </div>
    <div class="content fr">
      <%= render 'index_right' %>
    </div>
  </div>
</div>
<div id="star"></div>
<% content_for:script do %>
    <script type="text/javascript">
        seajs.use(['place/latest/place', 'slides'], function (place, slides) {
            place.index();
            //滚动焦点图插件
            slides($);
            $("#gui_focus").slides({
                play: 5000,
                pause: 2500,
                hoverPause: true
            });
        });
    </script>
<% end %>

app/views/places/new.html.erb
<div class="boxshadow">
  <div style="background:#fff;height: 210px;border-bottom: 1px solid #ddd">sssss</div>
  <div style="background:#F0F0F0;height: 40px;border-top:1px solid #fff ">sssss</div>
</div>

<div class="main">

  <h1>New place</h1>

  <%= render 'form' %>

  <%= link_to 'Back', places_path %>
</div>

app/views/places/photos.html.erb
<% content_for:style do %>
    <link rel="stylesheet" href="/css/place/style.css"/>
    <link rel="stylesheet" href="/css/place/style4.css"/>
<% end %>

<div class="qyer_head_crumbg">
  <div class="qyer_head_crumb">
    <span class="text"><a href="<%= main_path %>">首页</a></span>
    <span class="space">&gt;</span>
    <span class="text drop"><a href="<%= places_path %>">目的地</a><em class="arrow" data="crumb_continents"></em></span>
    <% if @place.province && @place.city %>
        <span class="space">&gt;</span><span class="text drop"><a href="<%= city_places_path @place.city.pinyin %>" data-bn-ipg="3-3"><%= @place.province.name %></a><em class="arrow" data="crumb_country"></em></span><span class="space">&gt;</span><span class="text drop"><a href="<%= city_places_path @place.city.pinyin %>" data-bn-ipg="3-4"><%= @place.city.name %></a><em class="arrow" data="crumb_city"></em></span>
    <% end %>
    <span class="space">&gt;</span>

    <h1 class="current"><%= @place.name %></h1>
  </div>
</div>

<div class="pl_topbox_wrap">
  <div class="pl_topbox clearfix">
    <div class="pl_topbox_name">
      <div class="clearfix">
        <p class="pl_topbox_cn fontYaHei">
          <a href="<%= place_path @place %>"><%= @place.province.name %>,<%= @place.city.name %></a></p>
      </div>
      <div class="clearfix">
        <p class="pl_topbox_cn fontYaHei"><a href="<%= place_path @place %>"><%= @place.name %></a></p>
      </div>
    </div>
    <div class="pl_topbox_right">
      <ul class="pl_topbox_btn">
        <li class="pl_topbox_want" id="pl_topbox_want">
          <span class="tips">+1</span>
          <a href="javascript:void(0);" class="click" id="doings_planto_button" title="<%= @place.wantgoto_num.to_i.to_s %>人想去这里">想去</a>
        </li>
        <li class="pl_topbox_been" id="pl_topbox_been">
          <span class="tips">+1</span>
          <a href="javascript:void(0);" class="click" id="doings_beento_button" title="<%= @place.beengo_num.to_i.to_s %>人去过这里">去过</a>
        </li>
      </ul>
      <p class="pl_topbox_numbeen fontYaHei"><em id="doings_beento_counts_big"><%= @place.beengo_num.to_i.to_s %></em>人去过这里
      </p>
    </div>
  </div>
</div>

<div class="main">
  <div class="clearfix">
    <h3 class="ui_title fr"><a href="http://place.qyer.com/paris/" class="fontSong cRed">返回城市首页 &lt;&lt;</a></h3>

  </div>
  <div class="place_album_sharebox clearfix">
    <div class="place_album_sharebox_text fl">欢迎在这里和旅行者分享你的精彩照片，优秀作品将可能会被选入这个城市的官方相册，快来分享吧！</div>
    <div class="place_album_sharebox_button fr">
      <a class="ui_button14 _jsurl" rel="nofollow" href="http://user.qyer.com/album_action_upload_city_20">我要添加照片</a>
    </div>
  </div>
  <div class="ui_seqencing mt20">排序:&nbsp;&nbsp;
    <a href="http://place.qyer.com/paris/photo/" class="ui_seqencing_item ui_seqencing_item_current">最热门的<span></span></a>&nbsp;&nbsp;|&nbsp;&nbsp;<a href="http://place.qyer.com/paris/photo/new/" class="ui_seqencing_item">最新添加<span></span></a>
  </div>
  <ul class="place_album_list clearfix mt10" id="photo_list_item">
    <% @photos.each do |p| %>
        <li class="place_album_list_item">
          <div><a href=""><img src="<%= p.img_path.sub(/thumb/, 'sqr_thumb') %>"></a></div>
          <div class="place_album_list_item_mask"></div>
          <div class="place_album_list_item_tips">
            <div>
              <span class="icon_album_look">174</span>
            </div>
            <div>巴黎</div>
            <div>来自：<%= p.user.username %></div>
          </div>
        </li>
    <% end %>
  </ul>
  <div class="place_album_page">
    <div class="place_album_page_position">
      <ul class="pagination">
        <div class="ui_page">
          <a data-bn-ipg="pages-3" href="/paris/photo/page1/" class="ui_page_item ui_page_item_current">1</a>
          <a data-bn-ipg="pages-3" href="/paris/photo/page2/" class="ui_page_item">2</a>
          <a data-bn-ipg="pages-3" href="/paris/photo/page3/" class="ui_page_item">3</a>
          <a data-bn-ipg="pages-3" href="/paris/photo/page4/" class="ui_page_item">4</a>
          <a data-bn-ipg="pages-3" href="/paris/photo/page5/" class="ui_page_item">5</a>
          <a data-bn-ipg="pages-4" href="/paris/photo/page261/" class="ui_page_item" title="...261">...261</a>
          <a data-bn-ipg="pages-5" href="/paris/photo/page2/" class="ui_page_item ui_page_next" title="下一页">下一页</a>
        </div>
      </ul>
    </div>
  </div>
  <div class="cb"></div>
</div>

<script type="text/javascript">
    readyScript.photoTips = function () {
        var $photos_list_items = $("#photo_list_item li.place_album_list_item");
        $photos_list_items.on("mouseover",function () {
            $(this).find('.place_album_list_item_mask').show();
            $(this).find('.place_album_list_item_tips').show();
        }).mouseout(function () {
                    $(this).find('.place_album_list_item_mask').hide();
                    $(this).find('.place_album_list_item_tips').hide();
                });
    }

</script>